{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN  apt-get update \
    && apt-get install -y bash python3 \
    && apt-get clean