name: build
run-name: ${{ github.run_number }} - CI by event ${{ github.event_name }} initiated ${{ github.triggering_actor }}
on: [push]
env: 
  VENV_DIR: .venv
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Mount cache
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: ${{ env.VENV_DIR }}
          key: ansible-role-template-${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ansible-role-template-${{ runner.os }}-venv-
      
      - name: Create venv and install Dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python3 -m venv ${{ env.VENV_DIR }}
          source ${{ env.VENV_DIR }}/bin/activate
          python3 -m pip install -r requirements.txt

      - name: Setup venv
        run: |
          source ${{ env.VENV_DIR }}/bin/activate
          echo "VIRTUAL_ENV=${VIRTUAL_ENV}" >> $GITHUB_ENV
          echo "${VIRTUAL_ENV}/bin" >> $GITHUB_PATH

      - name: Run Test
        run: molecule test